### ISSUE TITLE
MAF file format

### ISSUE THREAD

**Issue by Ashiq-M** [taylor-lab/hotspots#1]
We tried to run this tool for our Lung genome analysis. We used standard MAF with 32 columns and this is not working. Can you please let know  which columns in MAF are necessary to run this analysis?
We will appreciate your help !
Thanks,
Ashiq

**Comment by ckandoth** [comment]
Sorry for the late response, but we can safely blame the holidays. The hotspot tool should tell you which required columns are missing. Standard 34-column MAF format does not include important information about each variant, including codon change. So you will need to generate that first. The recommended method to generate a compatible MAF is to use the `maf2maf.pl` tool at https://github.com/mskcc/vcf2maf
