### ISSUE TITLE
genomic coordinates of true positive sites

### ISSUE THREAD

**Issue by patidarr** [taylor-lab/hotspots#2]
Hi,

Would it be possible to get genomic coordinates of sites in https://github.com/taylor-lab/hotspots/blob/master/true_positive_hotspots.txt maybe maf or vcf format?

Thanks,
Rajesh

**Comment by ckandoth** [comment]
Each protein change listed in [true_positive_hotspots.txt](https://github.com/taylor-lab/hotspots/blob/master/true_positive_hotspots.txt), could have multiple possible genomic loci and allele changes. So we store those separately in the main MAF. A link to download the main MAF can be [found here](https://github.com/taylor-lab/hotspots/blob/master/LINK_TO_MUTATIONAL_DATA). File is ~1.8G in size.

**Comment by patidarr** [comment]
Thanks Cyriac,

One more question.
In the supplement table 2 of the paper. there are some sites for example:
ANKZF1 A650 NA V:4|**A:1** 0.0043 5 5 Level=1 ucs:1|skcm:1|paad:1|luad:1|lgg:1

Does that mean A650A is also considered as a mutation here? at the same time the big maf file does not contain any A650A site.

There are few more looks like synonymous to me but in this table. 
TGFBRAP1 P824 NA S:2|L:2|**P:1**|F:1
TACC3 P417 NA S:4|**P:2** 0.0056 6 3 Level=1 skcm:4|luad:1|acc:1
ATP6V1B2 P352 NA S:4|**P:1** 0.0056 5 3 Level=1 skcm:3|nbl:1|cscc:1

Could you please explain?

Thanks very much,
Rajesh

**Comment by changmt** [comment]
Yes, we considered silent mutation as a mutation in the algorithm. 
RE: silent mutations in the MAF file, I confirmed the silent mutations you mentioned are in the MAF file uploaded. Specifically, ANKZF1 A650A was found in MEL-JWCI-WGS-38, TGFBRAP1 P824P in TCGA-FS-A1ZK-06, TACC3 P417P in TCGA-OR-A5JU-01 and TCGA-55-8514-01, and ATP6V1B2 P352P in TCGA-EE-A182-06.

**Comment by patidarr** [comment]
Got it,

Thanks.
