### ISSUE TITLE
Cannot access full mutational data

### ISSUE THREAD

**Issue by yboursin** [taylor-lab/hotspots#3]
Hi,

It seems like your googledrive link is down. Could you provide another link ?

> Access to the full mutational data can be obtained here:  https://googledrive.com/host/0B1tQDSL9FmNLTmo1dl9SRF9USUE
> Note, file is ~1.8G in size. md5sum: 94a3538afdbfbc8b52c75914c60c9f78

Thank you for this work, it's great !

Kind regards,

Y. Boursin, Gustave Roussy

**Comment by yboursin** [comment]
Seems like this was a google temporary issue. Sorry for the disturbance.

**Comment by ckandoth** [comment]
Just a heads up that Google will soon be retiring this capability of downloading files directly via googledrive.com.

**Comment by yboursin** [comment]
Didn't know that, thank's for the heads up.

**Comment by ckandoth** [comment]
I have changed [the link](https://github.com/taylor-lab/hotspots/blob/master/LINK_TO_MUTATIONAL_DATA) to keep it future proof. The downside is that command-line users won't be able to able to `wget` or `curl` the 1.8GB file directly into their compute clusters. They will need to use a browser to download the file.
