### ISSUE TITLE
Code makes assumption not valid for official TCGA MAF

### ISSUE THREAD

**Issue by ctokheim** [taylor-lab/hotspots#8]
Hi,

I'm getting an error originating from the amino acid length being NA.

It looks like from looking at the internals of the code that you assume the "Protein_position" column should be something like "position/length", where "position" is the amino acid position of the mutation and "length" is the total length of the protein. Despite a MAF file from TCGA containing a "Protein_position" column, it only contains the "position" part and not anything related to the protein length.

Collin

**Comment by ctokheim** [comment]
I left this out, but the MAF I'm referring to is here: https://synapse.org/MC3

**Comment by ctokheim** [comment]
I've fetched the ensembl protein lengths using the biomart R package, and incorporated that syntax into the "Protein_position" column. The algorithm starts running with that fix on the MAF.

**Comment by ckandoth** [comment]
Hi Collin. "Protein_position" in the format you described is [this output](https://github.com/mskcc/vcf2maf/blob/master/docs/vep_maf_readme.txt#L38) of the VEP annotator. You can use maf2maf from [the vcf2maf repo](https://github.com/mskcc/vcf2maf/releases), which runs VEP to standardize MAF files in a format usable by most MAF parsers.

**Comment by ctokheim** [comment]
Ok, good to know. Thanks Cyriac!
